#!/bin/sh -e
GCC4=$1
LIB_GMP=$2
LIB_MPFR=$3
LIB_MPC=$4
unset CWD; CWD=$PWD
unset PKG; PKG=$TMP/$GCC4-package
unpack_src $SRC $GCC4 $TMP
unpack_src $SRC $LIB_GMP $TMP
unpack_src $SRC $LIB_MPFR $TMP
unpack_src $SRC $LIB_MPC $TMP
mv $TMP/$LIB_GMP $TMP/$GCC4/gmp
mv $TMP/$LIB_MPFR $TMP/$GCC4/mpfr
mv $TMP/$LIB_MPC $TMP/$GCC4/mpc

cd $TMP/$GCC4
bzcat $CWD/patches/*.patch* | patch -p1
bzcat $CWD/patches/*.diff*  | patch -p1
zcat $CWD/patches/*.patch* | patch -p1
zcat $CWD/patches/*.diff*  | patch -p1


rm  -rf  $TMP/$GCC4-build
mkdir -p $TMP/$GCC4-build
cd $TMP/$GCC4-build

echo "ac_exeption_model_name=sjlj"		>>config.cache

CFLAGS="$CFLAGS  -fomit-frame-pointer " \
../$GCC4/configure \
    --prefix=/usr  \
    --disable-bootstrap  \
    --disable-nls  --disable-multilib   \
    --enable-languages=c,c++,lto \
    --enable-__cxa-atexit --enable-c99 --enable-threads=posix \
    --enable-shared --enable-static \
--without-cloog --without-isl --without-ppl \
--with-mpfr-include=$(pwd)/mpfr/src  --with-mpfr-lib=$(pwd)/mpfr/src/.libs  \
--build=$ID_BUILD --host=$ID_HOST --target=$TOOLS_PREFIX \
--with-local-prefix=$R/usr  --with-sysroot=$R \
--disable-libmudflap --disable-libssp --disable-libgomp --disable-decimal-float --disable-libquadmath \
--disable-libstdcxx-pch \

#--enable-ld=yes  --enable-gold=yes  \
#--cache-file=config.cache ac_exeption_model_name=sjlj


make -j $CPU_CORES 

rm -rf $PKG 
mkdir -p $PKG/lib$LIBDIRSUFFIX

make DESTDIR=$PKG install

#cd $TMP/$GCC4-build/gmp
#make DESTDIR=$PKG install

#cd $TMP/$GCC4-build/mpfr
#make DESTDIR=$PKG install

#cd $TMP/$GCC4-build/mpc
#make DESTDIR=$PKG install

cd $PKG/
/sbin/makepkg -l y -c n $P/$GCC4-$TOOLS_PREFIX-st0-3.txz
