#!/bin/sh
mkdir ./source
cd ./source
wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.4.211.tar.xz
wget https://mirrors.edge.kernel.org/pub/linux/devel/binutils/binutils-2.24.51.0.3.tar.xz
wget ftp://ftp.gnu.org/gnu/glibc/glibc-2.20.tar.xz
wget -t 2 -T 20  http://ftp.gnu.org/gnu/gcc/gcc-4.7.4/gcc-4.7.4.tar.bz2
wget ftp://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.bz2
wget http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.5.tar.bz2 
wget http://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
wget ftp://ftp.gnu.org/gnu/make/make-3.81.tar.bz2
wget busybox.net/downloads/busybox-1.22.1.tar.bz2 
cd ..