( cd bin ; rm -rf sh )
( cd bin ; ln -sf ../usr/bin/sh sh )
( cd usr/bin ; rm -rf kill )
( cd usr/bin ; ln -sf busybox kill )
( cd usr/bin ; rm -rf sum )
( cd usr/bin ; ln -sf busybox sum )
( cd usr/bin ; rm -rf unix2dos )
( cd usr/bin ; ln -sf busybox unix2dos )
( cd usr/bin ; rm -rf setserial )
( cd usr/bin ; ln -sf busybox setserial )
( cd usr/bin ; rm -rf sed )
( cd usr/bin ; ln -sf busybox sed )
( cd usr/bin ; rm -rf less )
( cd usr/bin ; ln -sf busybox less )
( cd usr/bin ; rm -rf chown )
( cd usr/bin ; ln -sf busybox chown )
( cd usr/bin ; rm -rf install )
( cd usr/bin ; ln -sf busybox install )
( cd usr/bin ; rm -rf stat )
( cd usr/bin ; ln -sf busybox stat )
( cd usr/bin ; rm -rf mknod )
( cd usr/bin ; ln -sf busybox mknod )
( cd usr/bin ; rm -rf chgrp )
( cd usr/bin ; ln -sf busybox chgrp )
( cd usr/bin ; rm -rf lzopcat )
( cd usr/bin ; ln -sf busybox lzopcat )
( cd usr/bin ; rm -rf lzma )
( cd usr/bin ; ln -sf busybox lzma )
( cd usr/bin ; rm -rf tac )
( cd usr/bin ; ln -sf busybox tac )
( cd usr/bin ; rm -rf pkill )
( cd usr/bin ; ln -sf busybox pkill )
( cd usr/bin ; rm -rf ed )
( cd usr/bin ; ln -sf busybox ed )
( cd usr/bin ; rm -rf rm )
( cd usr/bin ; ln -sf busybox rm )
( cd usr/bin ; rm -rf unlzma )
( cd usr/bin ; ln -sf busybox unlzma )
( cd usr/bin ; rm -rf dnsdomainname )
( cd usr/bin ; ln -sf busybox dnsdomainname )
( cd usr/bin ; rm -rf pidof )
( cd usr/bin ; ln -sf busybox pidof )
( cd usr/bin ; rm -rf sha256sum )
( cd usr/bin ; ln -sf busybox sha256sum )
( cd usr/bin ; rm -rf hush )
( cd usr/bin ; ln -sf busybox hush )
( cd usr/bin ; rm -rf killall )
( cd usr/bin ; ln -sf busybox killall )
( cd usr/bin ; rm -rf tee )
( cd usr/bin ; ln -sf busybox tee )
( cd usr/bin ; rm -rf head )
( cd usr/bin ; ln -sf busybox head )
( cd usr/bin ; rm -rf reset )
( cd usr/bin ; ln -sf busybox reset )
( cd usr/bin ; rm -rf df )
( cd usr/bin ; ln -sf busybox df )
( cd usr/bin ; rm -rf sh )
( cd usr/bin ; ln -sf bash sh )
( cd usr/bin ; rm -rf wget )
( cd usr/bin ; ln -sf busybox wget )
( cd usr/bin ; rm -rf bunzip2 )
( cd usr/bin ; ln -sf busybox bunzip2 )
( cd usr/bin ; rm -rf time )
( cd usr/bin ; ln -sf busybox time )
( cd usr/bin ; rm -rf lsusb )
( cd usr/bin ; ln -sf busybox lsusb )
( cd usr/bin ; rm -rf realpath )
( cd usr/bin ; ln -sf busybox realpath )
( cd usr/bin ; rm -rf fsync )
( cd usr/bin ; ln -sf busybox fsync )
( cd usr/bin ; rm -rf killall5 )
( cd usr/bin ; ln -sf busybox killall5 )
( cd usr/bin ; rm -rf cttyhack )
( cd usr/bin ; ln -sf busybox cttyhack )
( cd usr/bin ; rm -rf which )
( cd usr/bin ; ln -sf busybox which )
( cd usr/bin ; rm -rf pstree )
( cd usr/bin ; ln -sf busybox pstree )
( cd usr/bin ; rm -rf id )
( cd usr/bin ; ln -sf busybox id )
( cd usr/bin ; rm -rf setsid )
( cd usr/bin ; ln -sf busybox setsid )
( cd usr/bin ; rm -rf lzop )
( cd usr/bin ; ln -sf busybox lzop )
( cd usr/bin ; rm -rf gunzip )
( cd usr/bin ; ln -sf busybox gunzip )
( cd usr/bin ; rm -rf tail )
( cd usr/bin ; ln -sf busybox tail )
( cd usr/bin ; rm -rf mkdir )
( cd usr/bin ; ln -sf busybox mkdir )
( cd usr/bin ; rm -rf watch )
( cd usr/bin ; ln -sf busybox watch )
( cd usr/bin ; rm -rf free )
( cd usr/bin ; ln -sf busybox free )
( cd usr/bin ; rm -rf uudecode )
( cd usr/bin ; ln -sf busybox uudecode )
( cd usr/bin ; rm -rf printf )
( cd usr/bin ; ln -sf busybox printf )
( cd usr/bin ; rm -rf chmod )
( cd usr/bin ; ln -sf busybox chmod )
( cd usr/bin ; rm -rf dirname )
( cd usr/bin ; ln -sf busybox dirname )
( cd usr/bin ; rm -rf bzcat )
( cd usr/bin ; ln -sf busybox bzcat )
( cd usr/bin ; rm -rf printenv )
( cd usr/bin ; ln -sf busybox printenv )
( cd usr/bin ; rm -rf [ )
( cd usr/bin ; ln -sf busybox [ )
( cd usr/bin ; rm -rf beep )
( cd usr/bin ; ln -sf busybox beep )
( cd usr/bin ; rm -rf xargs )
( cd usr/bin ; ln -sf busybox xargs )
( cd usr/bin ; rm -rf expr )
( cd usr/bin ; ln -sf busybox expr )
( cd usr/bin ; rm -rf ttysize )
( cd usr/bin ; ln -sf busybox ttysize )
( cd usr/bin ; rm -rf renice )
( cd usr/bin ; ln -sf busybox renice )
( cd usr/bin ; rm -rf strings )
( cd usr/bin ; ln -sf busybox strings )
( cd usr/bin ; rm -rf hexdump )
( cd usr/bin ; ln -sf busybox hexdump )
( cd usr/bin ; rm -rf gzip )
( cd usr/bin ; ln -sf busybox gzip )
( cd usr/bin ; rm -rf uuencode )
( cd usr/bin ; ln -sf busybox uuencode )
( cd usr/bin ; rm -rf resize )
( cd usr/bin ; ln -sf busybox resize )
( cd usr/bin ; rm -rf readlink )
( cd usr/bin ; ln -sf busybox readlink )
( cd usr/bin ; rm -rf sync )
( cd usr/bin ; ln -sf busybox sync )
( cd usr/bin ; rm -rf cksum )
( cd usr/bin ; ln -sf busybox cksum )
( cd usr/bin ; rm -rf comm )
( cd usr/bin ; ln -sf busybox comm )
( cd usr/bin ; rm -rf stty )
( cd usr/bin ; ln -sf busybox stty )
( cd usr/bin ; rm -rf true )
( cd usr/bin ; ln -sf busybox true )
( cd usr/bin ; rm -rf hostname )
( cd usr/bin ; ln -sf busybox hostname )
( cd usr/bin ; rm -rf whois )
( cd usr/bin ; ln -sf busybox whois )
( cd usr/bin ; rm -rf ln )
( cd usr/bin ; ln -sf busybox ln )
( cd usr/bin ; rm -rf tty )
( cd usr/bin ; ln -sf busybox tty )
( cd usr/bin ; rm -rf chroot )
( cd usr/bin ; ln -sf busybox chroot )
( cd usr/bin ; rm -rf catv )
( cd usr/bin ; ln -sf busybox catv )
( cd usr/bin ; rm -rf unzip )
( cd usr/bin ; ln -sf busybox unzip )
( cd usr/bin ; rm -rf fgrep )
( cd usr/bin ; ln -sf busybox fgrep )
( cd usr/bin ; rm -rf seq )
( cd usr/bin ; ln -sf busybox seq )
( cd usr/bin ; rm -rf mv )
( cd usr/bin ; ln -sf busybox mv )
( cd usr/bin ; rm -rf cut )
( cd usr/bin ; ln -sf busybox cut )
( cd usr/bin ; rm -rf dos2unix )
( cd usr/bin ; ln -sf busybox dos2unix )
( cd usr/bin ; rm -rf date )
( cd usr/bin ; ln -sf busybox date )
( cd usr/bin ; rm -rf clear )
( cd usr/bin ; ln -sf busybox clear )
( cd usr/bin ; rm -rf more )
( cd usr/bin ; ln -sf busybox more )
( cd usr/bin ; rm -rf basename )
( cd usr/bin ; ln -sf busybox basename )
( cd usr/bin ; rm -rf sort )
( cd usr/bin ; ln -sf busybox sort )
( cd usr/bin ; rm -rf patch )
( cd usr/bin ; ln -sf busybox patch )
( cd usr/bin ; rm -rf top )
( cd usr/bin ; ln -sf busybox top )
( cd usr/bin ; rm -rf cal )
( cd usr/bin ; ln -sf busybox cal )
( cd usr/bin ; rm -rf wc )
( cd usr/bin ; ln -sf busybox wc )
( cd usr/bin ; rm -rf cp )
( cd usr/bin ; ln -sf busybox cp )
( cd usr/bin ; rm -rf cpio )
( cd usr/bin ; ln -sf busybox cpio )
( cd usr/bin ; rm -rf bash )
( cd usr/bin ; ln -sf busybox bash )
( cd usr/bin ; rm -rf zcat )
( cd usr/bin ; ln -sf busybox zcat )
( cd usr/bin ; rm -rf sha1sum )
( cd usr/bin ; ln -sf busybox sha1sum )
( cd usr/bin ; rm -rf sha512sum )
( cd usr/bin ; ln -sf busybox sha512sum )
( cd usr/bin ; rm -rf false )
( cd usr/bin ; ln -sf busybox false )
( cd usr/bin ; rm -rf echo )
( cd usr/bin ; ln -sf busybox echo )
( cd usr/bin ; rm -rf env )
( cd usr/bin ; ln -sf busybox env )
( cd usr/bin ; rm -rf base64 )
( cd usr/bin ; ln -sf busybox base64 )
( cd usr/bin ; rm -rf pwdx )
( cd usr/bin ; ln -sf busybox pwdx )
( cd usr/bin ; rm -rf touch )
( cd usr/bin ; ln -sf busybox touch )
( cd usr/bin ; rm -rf dmesg )
( cd usr/bin ; ln -sf busybox dmesg )
( cd usr/bin ; rm -rf hd )
( cd usr/bin ; ln -sf busybox hd )
( cd usr/bin ; rm -rf bzip2 )
( cd usr/bin ; ln -sf busybox bzip2 )
( cd usr/bin ; rm -rf sha3sum )
( cd usr/bin ; ln -sf busybox sha3sum )
( cd usr/bin ; rm -rf test )
( cd usr/bin ; ln -sf busybox test )
( cd usr/bin ; rm -rf yes )
( cd usr/bin ; ln -sf busybox yes )
( cd usr/bin ; rm -rf unlzop )
( cd usr/bin ; ln -sf busybox unlzop )
( cd usr/bin ; rm -rf du )
( cd usr/bin ; ln -sf busybox du )
( cd usr/bin ; rm -rf dc )
( cd usr/bin ; ln -sf busybox dc )
( cd usr/bin ; rm -rf find )
( cd usr/bin ; ln -sf busybox find )
( cd usr/bin ; rm -rf awk )
( cd usr/bin ; ln -sf busybox awk )
( cd usr/bin ; rm -rf split )
( cd usr/bin ; ln -sf busybox split )
( cd usr/bin ; rm -rf usleep )
( cd usr/bin ; ln -sf busybox usleep )
( cd usr/bin ; rm -rf rmdir )
( cd usr/bin ; ln -sf busybox rmdir )
( cd usr/bin ; rm -rf lzcat )
( cd usr/bin ; ln -sf busybox lzcat )
( cd usr/bin ; rm -rf hostid )
( cd usr/bin ; ln -sf busybox hostid )
( cd usr/bin ; rm -rf uname )
( cd usr/bin ; ln -sf busybox uname )
( cd usr/bin ; rm -rf unexpand )
( cd usr/bin ; ln -sf busybox unexpand )
( cd usr/bin ; rm -rf md5sum )
( cd usr/bin ; ln -sf busybox md5sum )
( cd usr/bin ; rm -rf nohup )
( cd usr/bin ; ln -sf busybox nohup )
( cd usr/bin ; rm -rf ls )
( cd usr/bin ; ln -sf busybox ls )
( cd usr/bin ; rm -rf cmp )
( cd usr/bin ; ln -sf busybox cmp )
( cd usr/bin ; rm -rf grep )
( cd usr/bin ; ln -sf busybox grep )
( cd usr/bin ; rm -rf who )
( cd usr/bin ; ln -sf busybox who )
( cd usr/bin ; rm -rf expand )
( cd usr/bin ; ln -sf busybox expand )
( cd usr/bin ; rm -rf diff )
( cd usr/bin ; ln -sf busybox diff )
( cd usr/bin ; rm -rf uniq )
( cd usr/bin ; ln -sf busybox uniq )
( cd usr/bin ; rm -rf lsof )
( cd usr/bin ; ln -sf busybox lsof )
( cd usr/bin ; rm -rf unxz )
( cd usr/bin ; ln -sf busybox unxz )
( cd usr/bin ; rm -rf pwd )
( cd usr/bin ; ln -sf busybox pwd )
( cd usr/bin ; rm -rf groups )
( cd usr/bin ; ln -sf busybox groups )
( cd usr/bin ; rm -rf mktemp )
( cd usr/bin ; ln -sf busybox mktemp )
( cd usr/bin ; rm -rf dd )
( cd usr/bin ; ln -sf busybox dd )
( cd usr/bin ; rm -rf ps )
( cd usr/bin ; ln -sf busybox ps )
( cd usr/bin ; rm -rf getopt )
( cd usr/bin ; ln -sf busybox getopt )
( cd usr/bin ; rm -rf ash )
( cd usr/bin ; ln -sf busybox ash )
( cd usr/bin ; rm -rf lspci )
( cd usr/bin ; ln -sf busybox lspci )
( cd usr/bin ; rm -rf mkfifo )
( cd usr/bin ; ln -sf busybox mkfifo )
( cd usr/bin ; rm -rf xz )
( cd usr/bin ; ln -sf busybox xz )
( cd usr/bin ; rm -rf fold )
( cd usr/bin ; ln -sf busybox fold )
( cd usr/bin ; rm -rf users )
( cd usr/bin ; ln -sf busybox users )
( cd usr/bin ; rm -rf egrep )
( cd usr/bin ; ln -sf busybox egrep )
( cd usr/bin ; rm -rf whoami )
( cd usr/bin ; ln -sf busybox whoami )
( cd usr/bin ; rm -rf nice )
( cd usr/bin ; ln -sf busybox nice )
( cd usr/bin ; rm -rf pgrep )
( cd usr/bin ; ln -sf busybox pgrep )
( cd usr/bin ; rm -rf vi )
( cd usr/bin ; ln -sf busybox vi )
( cd usr/bin ; rm -rf [[ )
( cd usr/bin ; ln -sf busybox [[ )
( cd usr/bin ; rm -rf od )
( cd usr/bin ; ln -sf busybox od )
( cd usr/bin ; rm -rf sleep )
( cd usr/bin ; ln -sf busybox sleep )
( cd usr/bin ; rm -rf logname )
( cd usr/bin ; ln -sf busybox logname )
( cd usr/bin ; rm -rf fstrim )
( cd usr/bin ; ln -sf busybox fstrim )
( cd usr/bin ; rm -rf cat )
( cd usr/bin ; ln -sf busybox cat )
( cd usr/bin ; rm -rf tar )
( cd usr/bin ; ln -sf busybox tar )
( cd usr/bin ; rm -rf xzcat )
( cd usr/bin ; ln -sf busybox xzcat )
( cd usr/bin ; rm -rf tr )
( cd usr/bin ; ln -sf busybox tr )
